apiVersion: v1
kind: ConfigMap
metadata:
  name: fscrawler
  namespace: staging
  labels:
    app: fscrawler
    env: staging
data:
  _settings.yaml: |
    ---
    name: "fscrawler_rest"
    fs:
      url: "/tmp/es"
      update_rate: "15m"
      excludes:
      - "*/~*"
      json_support: false
      filename_as_id: false
      add_filesize: true
      remove_deleted: true
      add_as_inner_object: true
      store_source: true
      index_content: true
      attributes_support: true
      raw_metadata: true
      xml_support: true
      index_folders: true
      lang_detect: true
      continue_on_error: true
      ocr:
        language: "eng"
        enabled: true
        pdf_strategy: "ocr_and_text"
      follow_symlinks: false
    elasticsearch:
      nodes:
      - url: "http://elasticsearch:9200"
      bulk_size: 100
      flush_interval: "5s"
      byte_size: "10mb"
    rest:
      url: "http://0.0.0.0:8890/fscrawler"
