apiVersion: v1
kind: ConfigMap
metadata:
  name: ti-api
  namespace: staging
  labels:
    app: ti-api
    env: staging
data:
  config.yml: |
    config:
      network:
        ip: 0.0.0.0
        port: 8080
        write_timeout: 15
        read_timeout: 15