apiVersion: v1
kind: ConfigMap
metadata:
  name: ti-api
  namespace: staging
  labels:
    app: ti-api
    env: staging
data:
  # TODO: Change test-secret to use env-variable
  config.yml: |
    config:
      test:
        run: true
        secret: super-secret
      network:
        ip: 0.0.0.0
        port: 8080
        write_timeout: 15
        read_timeout: 15
      db:
        urls:
          - http://elasticsearch:9200
      authentication:
        api_key: ${AUTH_API_KEY}
        credentials_file: /etc/secret-volume/auth-credentials-file.json
      filestore:
        base_path: ./
      indexing:
        fscrawler_url: http://fscrawler:8890/fscrawler
