apiVersion: v1
kind: ConfigMap
metadata:
  name: ti-api
  namespace: staging
  labels:
    app: ti-api
    env: staging
data:
  config.yml: |
    config:
      test:
        run: true
        secret: ${TEST_SECRET}
      network:
        ip: 0.0.0.0
        port: 8080
        write_timeout: 15
        read_timeout: 15
      authentication:
        api_key: ${AUTH_API_KEY}
        credentials_file: /etc/secret-volume/auth-credentials-file.json
