apiVersion: v1
kind: Service
metadata:
  name: test-console
  namespace: staging
  labels:
    app: test-console
    env: staging
spec:
  selector:
    app: test-console
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
