apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: staging
  labels:
    app: elasticsearch
    env: staging
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - name: transport
    port: 9300