apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: staging
  labels:
    app: elasticsearch
    env: staging
data:
  elasticsearch.yml: |
    cluster.name: elastic-cluster
    node.name: elastic-node
    network.host: 0.0.0.0
    discovery.type: single-node
  ES_JAVA_OPTS: -Xms512m -Xmx512m
