apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: staging
  labels:
    app: elasticsearch
    env: staging
data:
  elasticsearch.yml: |
    cluster.name: elastic-cluster
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
  ES_JAVA_OPTS: -Xms512m -Xmx512m