config:
  test:
    run: true
    secret: ${TEST_SECRET}
  network:
    ip: 0.0.0.0
    port: 8080
    write_timeout: 15
    read_timeout: 15
  db:
    urls:
      - http://elasticsearch:9200
  authentication:
    api_key: ${AUTH_API_KEY}
    credentials_file: ${AUTH_CREDENTIALS_FILE}
  filestore:
    base_path: ./
  indexing:
    fscrawler_url: http://fscrawler:8890/fscrawler