version: '3.4'
services:
  ti-api:
    build:
      context: ../
      dockerfile: Dockerfile
    image: timeline-investigator:local
    container_name: ti-api
    ports:
      - "8080:8080"
    entrypoint: ./api --cfg=/configs/config.yml
  
  ti-test:
    build:
      context: ../
      dockerfile: Dockerfile
      target: builder
    image: timeline-investigator:build
    container_name: ti-test
    depends_on: 
      - ti-api
    stdin_open: true
    tty: true    
    environment:
      - TEST_URL=http://ti-api:8080/api/
    entrypoint: go test ./tests
