version: '3.3'
services:
    rest-ti-api:
      build: ../
      image: timeline-investigator:latest
      ports:
        - "8080:8080"
      volumes:
        - type: bind
          source: ./config.yml
          target: /app/config.yml
