version: '3.4'
services:
  ti-api:
    build:
      context: ../
      dockerfile: Dockerfile
    image: timeline-investigator:local
    container_name: ti-api
    ports:
      - "8080:8080"
    entrypoint: ./api --cfg=/configs/config.yml
  
  ti-test:
    build:
      context: ../
      dockerfile: Dockerfile
      target: builder
    image: timeline-investigator:build
    container_name: ti-test
    depends_on: 
      - ti-api
    stdin_open: true
    tty: true    
    environment:
      - TEST_URL=http://ti-api:8080/api/
    entrypoint: go test ./tests

  kube:
    image: simonjansson/gcloud-kubectl:latest
    container_name: kube
    environment:
      - CLOUDSDK_API_KEY=ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGltZWxpbmUtaW52ZXN0aWdhdG9yIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMTNhODVlYjhmNzA4OTI3MjU0ZjcwNjVmMjRkYTlhMDZkOTRhMjU4OSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZBSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS1l3Z2dTaUFnRUFBb0lCQVFDUFRabnNtd3F5N21OQlxuZGxnVENnaER5ZXZ6SkxSbEZ4ZGIxWWdKZGQzZE1PMkdwU3ptNk1GRHVvV0ZzQW1hUnBaakk1cXl3enNMR2ZPQ1xud3NTNE9KNW9HZ1VzQ2ljcVNOSEI5V3lkcUh5OVFvaWRaZTk4OW9jQ3Zkem5yMnJXL0dYdURDV25JT0xRaTZXM1xuVVJEWFhScStDb1hWc21ORUkxVjdYUklqMVg0YVZuTnVFMnRlWUI0VGNxYldNWWRCRWZmSXUvaHdveDhDenVpSlxuaVVLM3Azd0hkc1cwVm9MR0xtdzZBS0U0aU1zL2pKeUgxV1ZrSUVjcUl2T29ZanM4SWFsSlpBZGRROGxWeHdsTlxuby9CbU5JQUxXbnpxUDZNNllqbFdYMHlpMTd3RVZYdTZ6b3JScWZjU1c4VUpFSkZkYmV5NlB0aXFpWENaVmhnUlxuVXdoMzNCbGJBZ01CQUFFQ2dnRUFEclJ5MkJHc3ptR2g4OFMyRXZZVGxRa3lXaGZwSHZwNG5pYlNOODVOZnZZWFxuV1pxM2VkWm1ocEdzUStTbGg1dzRzR0dsN1RRVmFmVTJ4TE5CeG5tZzM2UFQ1Z29Bck5rZUZSNGZFQ3FLNmt6YVxuZ2ZSRTEvamdMOHJWMFR4eDVTK3ZNZmN6SWV4QStnOXFhTjQ3c1MzUG9iS291eDM4QzdEb2c2a3dSRmNUQXBhM1xuSUFCMFdGMTBvYkJxeDFXU3NwQkFIOEpndTdxRDAyOXZYT1NQODZQdm81R0pHbi9hNitCQWZzQS9nR0xwdVNWSFxuUkZxNFpQSDAwQWhRQ3Ziazg2bnR6KzFZMTVYdit5MkoxMm9LYys3MS85bzVVVXl0b0NpVC9xdzEzMFErNzBIaFxuczFoU095SzVzYmlXK1Fxd01MU0U3SWlESUVLR01RbzNGejlzc20vbjJRS0JnUURCZWw0OVRSRmFLakx2bElxcVxuSWd4cEJCQzBBZnpTdVpsVkdwWkFQL1c0Z0NxZjlTRDBGZjE2Y1BwL3hEc0dzd2hoVDJyN1hNTEJXRTFUckVEZVxuU0JsNXlKWE9CMmwzL2pFd2tySjVsc3F3eVZJOVNtMUFCWmNscXNaV0hNOXhoVy9MSnBITjZWMzFac3d1cU40YVxubXlRUUlTQUZndDJmTWRUSHpiWkJIbmZrSHdLQmdRQzluSGx3azg4RFNYcnVIczZrZVBBUDBKQ2FDbWp6ZWs1QVxuUHFVck1RSW1oWGF1UU9lZVRsQ0dvSFJUSlVMV29PSGNPQ1pTY0tVaXhSMkh6VVc0WG1VOXRTUTUxVEh0RzRpMlxuZU1tVE5ZZjJEaU4xdkV2Sko5ZS9UZkh4VkF2SkZrdmM2eHJwbmw5am1XNGpZOEFRWWN6SnR3WS9IeFRUMGJKRFxuT2tReStEakRSUUtCZ0hnQnVMWjVPUXdlSkozcUd1QlFZalk1S1VzZCtIMlVWWUV1RG9nbm8vZ2V0MUdrTUI1MlxuRFZXSEFqbUJzOE1DQlc2bVhnc3ZqRFYwMmZIT1pDWDd2cUdGUXpZWjd0ZFl1WllSUjlhWEszM2dRYngyajdFb1xuUm9vOGxPMFF6Ykx5TzFkY3d3OWZjc0ltVXZ1V0RyMmVBUTVvSFg2Tm4zMkE0U1JWZW5pRnQ0T3RBb0dBSGpPNVxuYUVReStqd1BGN1RTaDRJNEF0emUyNXFDNHgxOUwyQ0xJSmthMVpYMnRJVGtIK1Fya1hZbmNVTURKWHJVM3lZV1xuZkpVeXlKb0xQU0ZtVkpxOGw1cXQzWVJuQW5TYlR5MW9Oa21Wa1l6byt3ejJLV0Z1VFN1V09UR0EreFBSRzZ4YlxuU2hFTzhxZHkwckpGMnBZcGI0djJzOEU0cVJEQ3kxQ1JvbWpGYWQwQ2dZQU5oNUhLeU9YQndZazVndk96dCtFL1xuTi9lNWI5NDNvN05uTHB0aC8wd29reUtSYmFPYnZsQk80ZENVTThCMDA1d3JYV1VyTnY5dDFsb2tycFVKWnZUTFxuTkY2V3BCbmhid2E3ZjRGNmNwS3Uxc0xEeWtPUy9tVzk0SUhWdGlSTmhpUDdoeldZTjV2MUdtTmk1eGkxQTdyV1xubmwrVkhOUnRXVGZYZXFRV01HVjBJQT09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAic3ZjLWNpQHRpbWVsaW5lLWludmVzdGlnYXRvci5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTMwNDg3NDc0OTI2MTIwNDIxNTEiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3N2Yy1jaSU0MHRpbWVsaW5lLWludmVzdGlnYXRvci5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
      - CLOUDSDK_COMPUTE_ZONE=europe-north1-a
      - CLOUDSDK_CONTAINER_CLUSTER=cluster-1
      - CLOUDSDK_CORE_PROJECT=timeline-investigator
    command: >
      echo hello &&
      kubectl get pods -n staging
    

